In [1]:
from qplcomp import *
import numpy as np

Generating LALR tables


## Functionality of Quantum Values

In [2]:
def Demo(code : str) -> None:
    A = Parser.parse(code)
    print("Input String: "+ code)
    print("Parsing Result: " + str(A))
    print("Value: ")
    print(A.eval())
    print()

## Expressions of (unindexed) Quantum Values

In [3]:
Demo("X[p]")
Demo("CX[p q]")

Input String: X[p]
Parsing Result: X[p]
Value: 
[[0. 1.]
 [1. 0.]][p]

Input String: CX[p q]
Parsing Result: CX[p q]
Value: 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]][p q]



In [4]:
# Demo("X[p q]")

In [5]:
# Demo("CX[p p]")

In [6]:
Demo("(P0 + P1)[p]")

Input String: (P0 + P1)[p]
Parsing Result: (P0+P1)[p]
Value: 
[[1. 0.]
 [0. 1.]][p]



In [7]:
Demo("(X Y)[p]")

Input String: (X Y)[p]
Parsing Result: (X Y)[p]
Value: 
[[0.+1.j 0.+0.j]
 [0.+0.j 0.-1.j]][p]



In [8]:
Demo("(X \\otimes X)[p q]")
Demo("(X ⊗ X)[p q]")

Input String: (X \otimes X)[p q]
Parsing Result: (X⊗ X)[p q]
Value: 
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]][p q]

Input String: (X ⊗ X)[p q]
Parsing Result: (X⊗ X)[p q]
Value: 
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]][p q]



In [9]:
Demo("(X X)†[p]")
Demo("(X X)^\\dagger[p]")

Input String: (X X)†[p]
Parsing Result: ((X X)†)[p]
Value: 
[[1. 0.]
 [0. 1.]][p]

Input String: (X X)^\dagger[p]
Parsing Result: ((X X)†)[p]
Value: 
[[1. 0.]
 [0. 1.]][p]



### Operations for Projectors

In [10]:
Demo("P0 \\vee Pm")
Demo("P0 ∧ Pm")

Input String: P0 \vee Pm
Parsing Result: (P0 ∨ Pm)
Value: 
[[1. 0.]
 [0. 1.]]

Input String: P0 ∧ Pm
Parsing Result: (P0 ∧ Pm)
Value: 
[[0. 0.]
 [0. 0.]]



## Expressions of Indexed Quantum Values

In [11]:
Demo("P0[p] + P1[p]")
Demo("P0[p] + (-P1)[q]")
Demo("I[p] - Pm[p]")

Input String: P0[p] + P1[p]
Parsing Result: (P0[p]+P1[p])
Value: 
[[1. 0.]
 [0. 1.]][p]

Input String: P0[p] + (-P1)[q]
Parsing Result: (P0[p]+(-P1)[q])
Value: 
[[ 1.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0. -1.]][p q]

Input String: I[p] - Pm[p]
Parsing Result: (I[p]-Pm[p])
Value: 
[[0.5 0.5]
 [0.5 0.5]][p]



In [12]:
Demo("CX[p q] CX[p q]")
Demo("H[q] CX[p q] H[q]")

Input String: CX[p q] CX[p q]
Parsing Result: (CX[p q] CX[p q])
Value: 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]][p q]

Input String: H[q] CX[p q] H[q]
Parsing Result: ((H[q] CX[p q]) H[q])
Value: 
[[ 1.00000000e+00  0.00000000e+00 -2.23711432e-17  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00 -2.23711432e-17]
 [-2.23711432e-17  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  2.23711432e-17  0.00000000e+00 -1.00000000e+00]][q p]



In [13]:
Demo("Y[q]^\\dagger Y[q]")

Input String: Y[q]^\dagger Y[q]
Parsing Result: ((Y[q]†) Y[q])
Value: 
[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]][q]



In [14]:
Demo("P0[p] \\otimes P1[q]")

Input String: P0[p] \otimes P1[q]
Parsing Result: (P0[p]⊗ P1[q])
Value: 
[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]][p q]



In [15]:
# Demo("CX[p q] \\otimes X[p]")

In [17]:
Demo("P0[p] \\wedge Pm[q]")
Demo("P0[p] \\vee Pm[q]")

Input String: P0[p] \wedge Pm[q]
Parsing Result: (P0[p] ∧ Pm[q])
Value: 
[[ 0.5 -0.5  0.   0. ]
 [-0.5  0.5  0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]][p q]

Input String: P0[p] \vee Pm[q]
Parsing Result: (P0[p] ∨ Pm[q])
Value: 
[[ 1.   0.   0.   0. ]
 [ 0.   1.   0.   0. ]
 [ 0.   0.   0.5 -0.5]
 [ 0.   0.  -0.5  0.5]][p q]

