In [16]:
from qplcomp import *
import numpy as np

In [17]:
def Demo(code : str) -> None:
    A = Parser.parse(code)
    print("Input String: "+ code)
    print("Parsing Result: " + str(A))
    print("Value: ")
    print(A.eval())
    print()

In [20]:
Demo("X[p]")
Demo("CX[p q]")

Input String: X[p]
Parsing Result: X[p]
Value: 
[[0. 1.]
 [1. 0.]][p]

Input String: CX[p q]
Parsing Result: CX[p q]
Value: 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]][p q]



In [28]:
# Demo("X[p q]")

In [29]:
# Demo("CX[p p]")

In [32]:
Demo("(P0 + P1)[p]")

Input String: (P0 + P1)[p]
Parsing Result: (P0+P1)[p]
Value: 
[[1. 0.]
 [0. 1.]][p]



In [33]:
Demo("(X Y)[p]")

Input String: (X Y)[p]
Parsing Result: (X Y)[p]
Value: 
[[0.+1.j 0.+0.j]
 [0.+0.j 0.-1.j]][p]



In [30]:
Demo("(X \\otimes X)[p q]")
Demo("(X ⊗ X)[p q]")

Input String: X \otimes X [p q]
Parsing Result: (X⊗ X)[p q]
Value: 
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]][p q]

Input String: X ⊗ X [p q]
Parsing Result: (X⊗ X)[p q]
Value: 
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]][p q]



In [38]:
Demo("(X X)†[p]")
Demo("(X X)^\\dagger[p]")

Input String: (X X)†[p]
Parsing Result: ((X X)†)[p]
Value: 
[[1. 0.]
 [0. 1.]][p]

Input String: (X X)^\dagger[p]
Parsing Result: ((X X)†)[p]
Value: 
[[1. 0.]
 [0. 1.]][p]

